source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!


target 'NNFrameTimer_Example', :exclusive => true do
  pod "NNFrameTimer", :path => "../"
  pod "NBULog"
end

target 'NNFrameTimer_Tests', :exclusive => true do
  pod "NNFrameTimer", :path => "../"

  
end
