source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '7.0'

target 'NNFrameTimer_Example', :exclusive => true do
  pod "NNFrameTimer", :path => "../"
end

target 'NNFrameTimer_Tests', :exclusive => true do
  pod "NNFrameTimer", :path => "../"

  
end
